using RecompOne.Runtime.Context;
using RecompOne.Runtime.Dispatch;
using RecompOne.Runtime.Memory;

namespace Recompiled;

// King's Field II's GAME.EXE, as the patches written for it call it.
//
// This repository started as a copy of the King's Field II port (verdite2) and
// now builds King's Field (JP, SLPS-00017), whose recompiled classes are
// KingsField_open and KingsField_game. The KF2 patches are kept, uninstalled,
// as the reference each KF1 equivalent is rebuilt from (docs/KF1.md, "What came
// across from King's Field II"); the ones that call a KF2 routine directly by
// its generated name compile against this table instead of generated/.
//
// Every entry is the KF2 address, dispatched. Nothing installed in the KF1
// build reaches one: KF2's GAME.EXE is never loaded, so a call would stop at
// the dispatcher as an unmapped address. Generated by hand from
// config/funcmaps/game.json (KF2's); regenerate if a KF2 patch calls another.
public static class KingsField2_game
{
    public static void Clip3FTP(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x8005CA48u);
    public static void Clip4FTP(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x8005CAC8u);
    public static void MulMatrix0(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x8005BCD8u);
    public static void MulMatrix2(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x8005BFD4u);
    public static void RotTrans(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x8005D968u);
    public static void ScaleMatrix(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x8005C538u);
    public static void SetColorMatrix(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x8005C7E0u);
    public static void SetFogNear(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x8005ED40u);
    public static void SetLightMatrix(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x8005C7B0u);
    public static void SetRotMatrix(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x8005C780u);
    public static void SetTransMatrix(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x8005C810u);
    public static void func_80014158(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x80014158u);
    public static void func_80014B88(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x80014B88u);
    public static void func_80014E90(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x80014E90u);
    public static void func_80014FE0(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x80014FE0u);
    public static void func_80015048(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x80015048u);
    public static void func_800158C8(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x800158C8u);
    public static void func_80015930(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x80015930u);
    public static void func_800172A4(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x800172A4u);
    public static void func_80022CAC(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x80022CACu);
    public static void func_80022DC4(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x80022DC4u);
    public static void func_80023638(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x80023638u);
    public static void func_800240B8(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x800240B8u);
    public static void func_80024154(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x80024154u);
    public static void func_80025D38(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x80025D38u);
    public static void func_80025DA8(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x80025DA8u);
    public static void func_80029E5C(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x80029E5Cu);
    public static void func_8002A264(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x8002A264u);
    public static void func_8002B6B4(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x8002B6B4u);
    public static void func_8002D3A8(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x8002D3A8u);
    public static void func_8002DDDC(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x8002DDDCu);
    public static void func_8002E064(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x8002E064u);
    public static void func_8002E0FC(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x8002E0FCu);
    public static void func_8002E190(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x8002E190u);
    public static void func_8002E1BC(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x8002E1BCu);
    public static void func_8002E1F0(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x8002E1F0u);
    public static void func_8002E22C(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x8002E22Cu);
    public static void func_8002E650(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x8002E650u);
    public static void func_8002E7CC(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x8002E7CCu);
    public static void func_8002E9B8(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x8002E9B8u);
    public static void func_8002EAEC(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x8002EAECu);
    public static void func_8002F214(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x8002F214u);
    public static void func_8002FECC(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x8002FECCu);
    public static void func_800302E8(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x800302E8u);
    public static void func_80030540(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x80030540u);
    public static void func_80030C94(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x80030C94u);
    public static void func_80031950(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x80031950u);
    public static void func_80031B1C(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x80031B1Cu);
    public static void func_80031C94(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x80031C94u);
    public static void func_80032588(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x80032588u);
    public static void func_80032AC4(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x80032AC4u);
    public static void func_80032CD8(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x80032CD8u);
    public static void func_80032D78(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x80032D78u);
    public static void func_80032DE8(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x80032DE8u);
    public static void func_80032EAC(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x80032EACu);
    public static void func_80032FAC(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x80032FACu);
    public static void func_8003309C(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x8003309Cu);
    public static void func_80034834(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x80034834u);
    public static void func_80034DA8(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x80034DA8u);
    public static void func_80035B48(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x80035B48u);
    public static void func_80037810(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x80037810u);
    public static void func_8003CE44(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x8003CE44u);
    public static void func_8005FCC8(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x8005FCC8u);
    public static void func_800605A4(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x800605A4u);
    public static void func_80060624(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x80060624u);
    public static void func_80060818(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x80060818u);
    public static void func_80060870(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x80060870u);
    public static void func_80060990(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x80060990u);
    public static void rcos(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x8005EC10u);
    public static void rsin(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x8005EB08u);
    public static void PadRead_game(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x8005F564u);
    public static void SetBackColor_game(CpuContext c, IMemory m) => Dispatcher.Call(c, m, 0x8005B208u);
}
